replicaCount: 1

image:
  repository: myregistry.azurecr.io/view-projector
  tag: latest
  pullPolicy: IfNotPresent

mongo:
  port: 27017

env:
  ASPNETCORE_ENVIRONMENT: Development

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "100m"
    memory: "256Mi"
