{{- if and .Values.sqlserver.enabled .Values.sqlserver.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sqlserver.persistence.size | quote }}
  {{- if .Values.sqlserver.persistence.hostPath.enabled }}
  volumeName: {{ .Chart.Name }}-data-pv
  storageClassName: ""
  {{- else if .Values.sqlserver.persistence.storageClassName }}
  storageClassName: {{ .Values.sqlserver.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
