{{- if .Values.sqlserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sqlserver.serviceName }}
spec:
  type: {{ .Values.sqlserver.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.sqlserver.serviceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.sqlserver.service.port }}
      targetPort: 1433
      {{- if eq (.Values.sqlserver.service.type | default "ClusterIP") "NodePort" }}
      nodePort: {{ .Values.sqlserver.service.nodePort }}
      {{- end }}
{{- end }}
