---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceAccountName }}-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","create","update","patch","delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get","list","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccountName }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.serviceAccountName }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
