apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-55"
stringData:
  appConnectionString: {{ .Values.sqlserver.appConnectionString | quote }}
  SQLSERVER_APP_USER: {{ .Values.sqlserver.credentials.appUser | quote }}
  SQLSERVER_APP_PASSWORD: {{ .Values.sqlserver.credentials.appPassword | quote }}