apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
  annotations:
    kubed.appscode.com/sync: "true"
    kubed.appscode.com/sync.pattern: ".*"
stringData:
  SQLSERVER_COMMANDS_APP_USER: {{ .Values.sqlservers.commands.appUser | quote }}
  SQLSERVER_COMMANDS_APP_PASSWORD: {{ .Values.sqlservers.commands.appPassword | quote }}
  SQLSERVER_COMMANDS_METRICS_USER: {{ .Values.sqlservers.commands.metricsUser | quote }}
  SQLSERVER_COMMANDS_METRICS_PASSWORD: {{ .Values.sqlservers.commands.metricsPassword | quote }}

  SQLSERVER_FAILED_VIEW_REBUILDER_APP_USER: {{ .Values.sqlservers.failedViewRebuilder.appUser | quote }}
  SQLSERVER_FAILED_VIEW_REBUILDER_APP_PASSWORD: {{ .Values.sqlservers.failedViewRebuilder.appPassword | quote }}
  SQLSERVER_FAILED_VIEW_REBUILDER_METRICS_USER: {{ .Values.sqlservers.failedViewRebuilder.metricsUser | quote }}
  SQLSERVER_FAILED_VIEW_REBUILDER_METRICS_PASSWORD: {{ .Values.sqlservers.failedViewRebuilder.metricsPassword | quote }}
