apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.resourcePrefix }}-master
  labels:
    app: {{ .Values.elasticsearch.resourcePrefix }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.elasticsearch.port }}
      name: http
  selector:
    app: {{ .Values.elasticsearch.resourcePrefix }}
    role: master
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.resourcePrefix }}-data
  labels:
    app: {{ .Values.elasticsearch.resourcePrefix }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.elasticsearch.port }}
      name: http
  selector:
    app: {{ .Values.elasticsearch.resourcePrefix }}
    role: data