apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.elasticsearch.resourcePrefix }}-data
  labels:
    app: {{ .Values.elasticsearch.resourcePrefix }}
    environment: {{ .Values.environment }}
    service_name: {{ .Values.otelCollector.serviceName }}
spec:
  serviceName: {{ .Values.elasticsearch.resourcePrefix }}-data
  replicas: {{ .Values.data.replicas }}
  selector:
    matchLabels:
      role: data
      app: {{ .Values.elasticsearch.resourcePrefix }}
  template:
    metadata:
      labels:
        app: {{ .Values.elasticsearch.resourcePrefix }}
        role: data
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image }}
          env:
            - name: ES_JAVA_OPTS
              value: {{ .Values.data.esJavaOpts | quote }}

            - name: ES_TRANSPORT_P12_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-transport
                  key: password

            - name: ES_HTTP_P12_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-http
                  key: password

          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data

            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            
            - name: es-ca
              mountPath: /usr/share/elasticsearch/config/certs/ca.crt
              subPath: ca.crt

            - name: es-transport
              mountPath: /usr/share/elasticsearch/config/certs/transport.p12
              subPath: transport.p12

            - name: es-http
              mountPath: /usr/share/elasticsearch/config/certs/http.p12
              subPath: http.p12

      volumes:
        - name: config
          configMap:
            name: {{ .Values.elasticsearch.resourcePrefix }}-config
        - name: es-ca
          secret:
            secretName: es-ca
        - name: es-transport
          secret:
            secretName: es-transport
        - name: es-http
          secret:
            secretName: es-http
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.data.persistence.size }}
        storageClassName: {{ .Values.data.persistence.storageClass | quote }}
