grafana-storage:
  grafana:
    persistence:
      storageClass: "hostpath"
      size: 5Gi
      claimName: grafana

  tempo:
    persistence:
      enabled: true
      storageClass: "nfs-client"
      size: 10Gi
      claimName: tempo-shared

grafana-ingress:
  grafana:
    servicePort: 80

  ingress:
    enabled: true
    host: grafana.localhost
    className: nginx
    tls:
      enabled: false
      secretName: ""
