elasticsearch:
  namespace: elasticsearch
  image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
  resourcePrefix: elasticsearch
  port: 9200

kafka:
  namespace: kafka
  userSecretName: "kafka-user"

ingress:
  ingressHttpPort: 30200
  ingressHttpsPort: 30443

apicurio:
  namespace: apicurio
  schemaRegistryUrlInternal: "http://apicurio-registry-service.apicurio.svc.cluster.local:8080/apis/ccompat/v7"

clickhouse:
  namespace: analytics
  resourcePrefix: clickhouse
  port: 8123
  database: eck1_analytics
  username: default
  password: default
  compress: "True"

observability:
  namespace: observability
  otlpService: "otel-collector-opentelemetry-collector"
  otlpPort: "4317"
  otlpProtocol: grpc
