environment: local 

replicaCount: 1

namespace: apicurio
image:
  operator: quay.io/apicurio/apicurio-registry-operator:1.1.3
  registry: quay.io/apicurio/apicurio-registry-kafkasql
  registryVersion: 2.6.4.Final

ingress:
  enabled: true
  host: registry.localhost
  className: nginx
  tls:
    enabled: false
    secretName: ""