replicaCount: 2

image:
  repository: localhost:5000/commands-api
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

sqlserver:
  appConnectionString: "Server=eck1-commandsapi-sql,1433;Database=ECK1.Commands;User Id=eck1_commands_app;Password=CmdApp!S3cure2026;TrustServerCertificate=True;Encrypt=False"
  credentials:
    appUser: "eck1_commands_app"
    appPassword: "CmdApp!S3cure2026"
