replicaCount: 1

image:
  repository: myregistry.azurecr.io/commands-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  ASPNETCORE_ENVIRONMENT: Development

sqlserver:
  database: "ECK1.Commands"
  host: "eck1-sqlserver"
  port: 1433
  appConnectionString: ""
  credentials:
    appUser: ""
    appPassword: ""

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "100m"
    memory: "256Mi"

dbup:
  enabled: true
  image:
    repository: localhost:5000/dbup
    tag: dev
