apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaceName }}
  labels:
    sync-global-vars: "true"
    sync-global-secrets: "true"
    sync-{{ .Values.elasticsearch.caSecretName }}: "true"
    sync-{{ .Values.elasticsearch.apiKeySecretName }}: "true"
