replicaCount: 1

image:
  repository: myregistry.azurecr.io/queries-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30180

mongo:
  connectionString: mongodb://eck1-viewprojector-mongo:27017
  
env:
  ASPNETCORE_ENVIRONMENT: Development
