{{- if .Values.sqlserver.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
stringData:
  metricsConnectionString: {{ .Values.sqlserver.metricsConnectionString | quote }}
  SQLSERVER_APP_USER: {{ .Values.sqlserver.credentials.appUser | quote }}
  SQLSERVER_APP_PASSWORD: {{ .Values.sqlserver.credentials.appPassword | quote }}
  SQLSERVER_METRICS_USER: {{ .Values.sqlserver.credentials.metricsUser | quote }}
  SQLSERVER_METRICS_PASSWORD: {{ .Values.sqlserver.credentials.metricsPassword | quote }}
{{- end }}