apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiKeyGenJob.rbac.serviceAccountName }}
---  

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.apiKeyGenJob.rbac.serviceAccountName }}-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.apiKeyGenJob.rbac.serviceAccountName }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.apiKeyGenJob.rbac.serviceAccountName }}

roleRef:
  kind: Role
  name: {{ .Values.apiKeyGenJob.rbac.serviceAccountName }}-role
  apiGroup: rbac.authorization.k8s.io
