apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.resourcePrefix }}-svc
spec:
  type: ClusterIP
  ports:
    - name: https
      port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
  selector:
    app: {{ .Values.elasticsearch.resourcePrefix }}
    role: master