replicaCount: 1

image:
  repository: myregistry.azurecr.io/commands-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  ASPNETCORE_ENVIRONMENT: Development

dbup:
  enabled: true
  image:
    repository: localhost:5000/dbup
    tag: dev
