{{ if .Values.runRedis }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-redis
        environment: {{ .Values.environment }}
        service_name: {{ .Values.redis.otelCollector.serviceName }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          ports:
            - containerPort: {{ .Values.redis.port }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"

          {{- if .Values.redis.resources }}
          resources: {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- end }}

      volumes:
{{- if .Values.redis.persistence }}
  {{- if .Values.redis.hostPath }}
        - name: redis-data
          hostPath:
            path: "{{ .Values.redis.hostPath }}"
            type: DirectoryOrCreate
  {{- else }}
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
  {{- end }}
{{- else }}
        - name: redis-data
          emptyDir: {}
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-redis
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      {{- if .Values.redis.nodePort }}
      nodePort: {{ .Values.redis.nodePort }}
      {{- end }}
      targetPort: {{ .Values.redis.port }}
{{- end }}
