{{- if eq .Values.environment "local" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.grafana.persistence.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.grafana.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
