apiVersion: v2
name: eck1-cache-short-term
description: A Helm chart for ECK1 Short Term Cache service
version: 0.1.0

dependencies:
  - name: config-merge
    version: 0.1.0
    repository: "file://../../common/helm/config-merge"

  - name: common-values
    version: 0.1.0
    repository: "file://../../common/helm/common-values"