{{- range .Values.plugins }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-{{ .name | lower }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}-{{ .name | lower }}
  template:
    metadata:
      annotations:
        rollme: {{ now | quote }}
      labels:
        app: {{ $.Chart.Name }}-{{ .name | lower }}
        environment: {{ $.Values.environment }}
        service_name: {{ $.Chart.Name }}-{{ .name | lower }}
    spec:

      {{- include "config-merge.initConfigAggregator" $ | nindent 6 }}

      containers:
        - name: integration-proxy-{{ .name | lower }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: Proxy__Plugin
              value: "{{ .name }}"

            - name: CacheService__ShortTerm__Url
              value: http://{{ include "common-values.cacheShortTermServiceName" . }}

            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            
            {{- with .spec.config.plain }}
            {{- include "render.env" (list . "") | nindent 12 }}
            {{- end }}

            {{- with .spec.config.configMap }}
            {{- include "render.env.configMap" (list . "") | nindent 12 }}
            {{- end }}

            {{- with .spec.config.secret }}
            {{- include "render.env.secret" (list . "") | nindent 12 }}
            {{- end }}

          {{- if $.Values.resources }}
          resources: {{- toYaml $.Values.resources | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: kafka-client-secret
              mountPath: /etc/secrets
              readOnly: true

            - name: plugins-lib
              mountPath: {{ $.Values.env.Proxy__PluginsDir }}
              readOnly: true

            {{- with .spec.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

            {{- include "config-merge.initConfigVolumeMounts" $ | nindent 12 }}

      volumes:
        - name: kafka-client-secret
          secret:
            secretName: kafka-client-secret
            
        {{- if $.Values.hostPath }}
        - name: plugins-lib
          hostPath:
            path: "{{ $.Values.hostPath }}"
            type: DirectoryOrCreate
        {{- else }}
        - name: plugins-lib
          persistentVolumeClaim:
            claimName: plugins-pvc
        {{- end }}

        {{- with .spec.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

        {{- include "config-merge.initConfigVolumes" $ | nindent 8 }}
---
{{- end }}
{{- include "config-merge.initConfigRbac" . }}