apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.environment }}-cluster
spec:
  kafka:
    version: "3.9.0"
    replicas: {{ .Values.replicaCount }}
    authorization:
      type: simple
    template:
      pod:
        priorityClassName: system-cluster-critical
    {{- if eq .Values.environment "local" }}
        securityContext:
          runAsUser: 0
          fsGroup: 0
    {{- end }}
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: internaltls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        tls: true
        authentication:
          type: scram-sha-512
        {{- if eq .Values.environment "local" }}
        type: nodeport
        configuration:
          bootstrap:
            nodePort: {{ $.Values.fixedPorts.bootstrapPort }}   
          brokers:
            {{- range $i := until (int .Values.replicaCount) }}
            - broker: {{ $i }}
              advertisedHost: 127.0.0.1
              advertisedPort: {{ index $.Values.fixedPorts.brokerPorts $i }}
              nodePort: {{ index $.Values.fixedPorts.brokerPorts $i }}
            {{- end }}
        {{- else }}
        type: loadbalancer
        {{- end }}
    storage:
      type: persistent-claim
      class: hostpath
      deleteClaim: false
      size: {{ .Values.kafka.storage.sizeKafka }}
    {{- with .Values.kafka.config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  zookeeper:
    replicas: 1
    template:
      terminationGracePeriodSeconds: 120
      readinessProbe:
        initialDelaySeconds: 120
      livenessProbe:
        initialDelaySeconds: 120
      pod:
        priorityClassName: system-cluster-critical
        hostnameAsFQDN: false
{{- if eq .Values.environment "local" }}
        securityContext:
          runAsUser: 0
          fsGroup: 0
{{- end }}
    storage:
      type: persistent-claim
      class: hostpath
      deleteClaim: false
      size: {{ .Values.kafka.storage.sizeZookeeper }}
    config:
      standaloneEnabled: true
      quorumListenOnAllIPs: true
    
  entityOperator:
    topicOperator: {}
    userOperator: {}
