sqlserver:
  enabled: true
  image:
    repository: mcr.microsoft.com/mssql/server
    tag: "2022-latest"
    pullPolicy: IfNotPresent
  mssqlPid: "Developer"
  podSecurityContext:
    fsGroup: 10001
    fsGroupChangePolicy: "OnRootMismatch"
  securityContext:
    runAsUser: 10001
    runAsGroup: 10001
  service:
    port: 1433
    type: ClusterIP
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: ""
    hostPath:
      enabled: false
      path: "/var/lib/mssql-data/commands"
  credentials:
    dbKey: SQLSERVER_COMMANDS_DB
    appUserKey: SQLSERVER_COMMANDS_APP_USER
    appPasswordKey: SQLSERVER_COMMANDS_APP_PASSWORD
    metricsUserKey: SQLSERVER_COMMANDS_METRICS_USER
    metricsPasswordKey: SQLSERVER_COMMANDS_METRICS_PASSWORD
