sqlserver:
  enabled: false
  image:
    repository: mcr.microsoft.com/mssql/server
    tag: "2022-latest"
    pullPolicy: IfNotPresent
  mssqlPid: "Developer"
  podSecurityContext:
    fsGroup: 10001
    fsGroupChangePolicy: "OnRootMismatch"
  securityContext:
    runAsUser: 10001
    runAsGroup: 10001
  service:
    port: 1433
    type: ClusterIP
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: ""
    hostPath:
      enabled: false
      path: "/var/lib/mssql-data/commands"
  resources: {}
  database: "ECK1.Commands"
  metricsConnectionString: ""
  credentials:
    appUser: ""
    appPassword: ""
    metricsUser: ""
    metricsPassword: ""
  otelCollector:
    enabled: true
    collectionInterval: 1m
    serviceName: "eck1-commandsapi"
